# define third-party library paths
# CHANGE YOUR CUDA PATH IF IT IS NOT THIS
CUDA_DIR := /usr/local/cuda-5.0
# CHANGE YOUR CUDA ARCH IF IT IS NOT THIS
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
    -gencode arch=compute_20,code=sm_21 \
    -gencode arch=compute_30,code=sm_30 \
    -gencode arch=compute_35,code=sm_35
# CHANGE YOUR MKL PATH IF IT IS NOT THIS
MKL_DIR := /home/jwa368/lib/mkl
# CHANGE YOUR MATLAB PATH IF IT IS NOT THIS
# your mex binary should be located at $(MATLAB_DIR)/bin/mex
MATLAB_DIR := /usr/local
# PUT ALL OTHER INCLUDE AND LIB DIRECTORIES HERE
INCLUDE_DIRS := /usr/include/c++/4.6/ /usr/local/include /usr/include/python2.7 \
    /usr/local/lib/python2.7/dist-packages/numpy/core/include /home/jwa368/lib/include \
    /usr/local/cuda-5.0/include
LIBRARY_DIRS := /usr/lib /usr/local/lib /home/jwa368/lib/lib /home/jwa368/lib/mkl/lib/intel64

# DEFINE THE CXX PATH
CXX=/usr/bin/g++

BUILD_DIR=build
DISTRIBUTE_DIR=distribute
